alpaca-7b:
  prompt_template: "/work/10159/rmarten/ls6/dcft/checkpoints/dcft-alpaca-reproduction-tacc-8xA100-40GB/prompt.txt"
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "/work/10159/rmarten/ls6/dcft/checkpoints/dcft-alpaca-reproduction-tacc-8xA100-40GB/" # local path
    model_kwargs:
      torch_dtype: 'bfloat16'
    max_new_tokens: 2048
    temperature: 0.7
    top_p: 1.0
    do_sample: True
  pretty_name: "Alpaca 7B Reproduction"
  link: "https://huggingface.co"
